Adds scripts, Dockerfiles, and GitHub Actions CI for checking formatting and autoformatting
flux-framework/dyad pull request #124
Opened 2024-10-17 16:10 UTC by ilumsden

Since I know there's been some issues with formatting (mostly due to my VSCode being stupid), I put together this PR to provide some new tools to help us with code formatting. This PR is heavily based on LLNL/Caliper#605, which I put together for the same reason.

This PR adds several scripts to the repo (all can be found in `scripts/formatting/`):
* `check-formatting.sh`: uses `clang-format` to check if the files in `src/` and `include/` are formatted correctly
* `autoformat.sh`: uses `clang-format` to autoformat the files in `src/` and `include/`
* `Dockerfile.check`: a Dockerfile that runs `check-formatting.sh` with `clang-format` v17.0.6
* `Dockerfile.format`: a Dockerfile that runs `autoformat.sh` with `clang-format` v17.0.6
* `check-formatting-docker.sh`: a script that builds and runs `Dockerfile.check`
* `autoformat-docker.sh`: a script that builds and runs `Dockerfile.format`

Additionally, this PR adds a new GitHub Actions workflow to check if code is formatted correctly. This script is essentially just a GitHub CI version of `Dockerfile.check`.

Finally, this PR adds the results of autoformatting the repo.

2024-10-17 17:23 UTC, hariharan-devarajan commented on include/dyad/stream/dyad_stream_core.hpp
> +#include <iostream>
Fix external before internal.

2024-10-17 17:32 UTC, hariharan-devarajan commented on scripts/formatting/autoformat-docker.sh
> +docker run --rm -v $(pwd):/home/jovyan --name caliper-autoformat-container caliper-autoformat
caliper

2024-10-17 17:40 UTC, ilumsden commented
- [ ] Add newline to end of each file
- [ ] Enforce ordering of includes
- [ ] Tweak formatting to preserve include groups and sort within each group
- [ ] Update docs to state that includes should be placed in newline-separated groups, which external groups (e.g., for C++ Standard Library and external tools) coming before internal groups
- [ ] Merge Dockerfiles into hierarchical Dockerfile (note: figure out how to run a specific tag for this type of Dockerfile)
   * This file shows how to do it for compose: https://github.com/hariharan-devarajan/hpc-aio/blob/dev/compose-dev.yaml. Need to figure out how to do this via CLI

2024-10-17 17:41 UTC, hariharan-devarajan requested changes
Lets address the comments we made during meeting.

2024-10-18 20:06 UTC, ilumsden commented
@hariharan-devarajan all the requested changes to this PR are complete.

2024-12-13 04:38 UTC, wangvsa commented on src/dyad/common/dyad_rc.h
I'm curious why the tabs before the comments in lines 29-31 were removed , whereas they were added for 57-62 lines? Is this done by autoformatting?

2024-12-13 15:37 UTC, ilumsden commented on src/dyad/common/dyad_rc.h
@wangvsa it seems to be basing the indent level off of groupings of fields. This is usually how clang-format does things. If you want, I can play around with clang-format settings to see if I can change that behavior.

2024-12-17 00:46 UTC, merged